apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-cache
  namespace: tasks-ginger-installer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: standard  # Adjust based on your cluster setup
