apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-binaries-and-upload-to-bucket
  namespace: tasks-ginger-installer
  annotations:
    x-ginger-task-namespace: "ginger-installer"  # Custom annotation
    x-ginger-task-trigger-branch: '["refs/heads/master"]'  # Allowed branches

spec:
  workspaces:
      - name: source
      - name: ssh-credentials  # Store SSH keys
      - name: ssh-config  # Store SSH setup
      - name: kubeconfig
      - name: buildah-cache  # Workspace for caching
  steps:
    - name: clone
      image: containers.gingersociety.org/secure-git-task-runner:latest
      script: |
        #!/bin/sh
        set -e  # Exit on error

        /usr/local/bin/configurator.sh
        
        git config --global init.defaultBranch main
        git clone git@source.gingersociety.org:ginger-installer.git /workspace/source/ginger-installer
        echo "Repository cloned successfully."

    - name: build
      image: alpine
      script: |
        #!/bin/sh
        set -e  # Exit on error
        cd /workspace/source/ginger-installer
        ls -la .
        cat Dockerfile


