apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-binaries-and-upload-to-bucket
  namespace: tasks-ginger-installer
  annotations:
    x-ginger-task-namespace: "ginger-installer"  # Custom annotation
    x-ginger-task-trigger-branch: '["refs/heads/master", "refs/heads/dev"]'  # Allowed branches

spec:
  steps:
    - name: clone
      image: alpine
      script: |
        #!/bin/sh
        echo "here we will build the project and upload the artifacts to a bucket"
